"""Parity gate for the static ``lessons.json`` shipped to the web build.

The zero-install web build reads its lessons from
``src/robolearn/assets/web/lessons.json`` instead of the pywebview bridge. That
file is generated by ``scripts/export_lessons.py`` from the same lesson library
and the same serialiser the desktop bridge uses. If a lesson YAML changes (or
the serialiser changes) and the JSON is not re-exported, the browser would ship
stale lessons while the desktop app shipped fresh ones.

This module is the gate that stops that: it re-runs the export in memory and
asserts the committed file is byte-identical. A stale ``lessons.json`` fails
here, which is exactly the signal to run ``python scripts/export_lessons.py``.
"""

from __future__ import annotations

import json
from typing import Any

from scripts.export_lessons import OUTPUT_PATH, render_json


def test_lessons_json_exists_and_parses() -> None:
    """The shipped JSON file is present and is valid JSON (a list of lessons)."""
    # Arrange / Act
    text = OUTPUT_PATH.read_text(encoding="utf-8")
    parsed: Any = json.loads(text)

    # Assert
    assert isinstance(parsed, list)
    assert parsed, "lessons.json must contain at least one lesson"


def test_lessons_json_matches_fresh_export_exactly() -> None:
    """The committed file must equal a fresh in-memory export byte-for-byte.

    This is the parity gate: a stale ``lessons.json`` (lessons changed but the
    export was not re-run) fails here. Re-run ``python scripts/export_lessons.py``
    to fix.
    """
    # Arrange: read bytes so no newline translation can mask a CRLF/LF drift
    # (the export writes LF; a byte compare is the real parity check).
    committed = OUTPUT_PATH.read_bytes()

    # Act: render straight from the live library + bridge serialiser.
    from scripts.export_lessons import build_lessons_payload

    fresh = render_json(build_lessons_payload()).encode("utf-8")

    # Assert
    assert committed == fresh, "lessons.json is stale -- run: python scripts/export_lessons.py"


def test_every_lesson_has_required_fields_and_a_success_criterion() -> None:
    """Each lesson carries the fields the UI consumes plus >=1 success criterion.

    ``id`` / ``title`` / ``starterCode`` / ``terrain`` are what the classroom
    panel renders and grades against; the success criterion is what makes a
    lesson actually completable rather than decorative.
    """
    # Arrange
    from robolearn.lessons.schema import load_library

    lessons = json.loads(OUTPUT_PATH.read_text(encoding="utf-8"))
    by_id = {lesson.id: lesson for lesson in load_library()}

    # Assert
    assert len(lessons) == len(by_id), "export and library disagree on lesson count"
    for entry in lessons:
        for field in ("id", "title", "starterCode", "terrain"):
            value = entry.get(field)
            assert isinstance(value, str) and value, (
                f"lesson {entry.get('id')!r} is missing a non-empty {field!r}"
            )
        # The success criteria live on the source lesson (the bridge shape the UI
        # consumes does not carry them); assert the shipped lesson is gradable.
        source = by_id[entry["id"]]
        assert len(source.success_criteria) >= 1, f"lesson {entry['id']!r} has no success criterion"
